version: '3'
services:
  db:
    image: postgres
    container_name: hello-app-db
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    container_name: hello-app-web
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/hello_app
    ports:
      - "3000:3000"
    depends_on:
      - db