version: '3'
services:
  sqlite3:
    image: sqlite3:1.4
    stdin_open: true
    tty: true
    volumes:
      - .:/rails_tutorial

  web:
    build: .
    command: /bin/sh #-c "rm -f tmp/pids/server.pid"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/rails_tutorial